### ISSUE TITLE
package on NPM is not compiled, no dist folder

### ISSUE THREAD

**Issue by mlabrum** [adamterlson/cairn#6]
Hey,

Just did a `npm install cairn --save` and it doesn't seem like the dist folder was included in the release?
![cairn](https://cloud.githubusercontent.com/assets/296106/12879240/1dfb5fec-ce80-11e5-8bde-beaabe9427d7.png)

Thanks

**Comment by adamterlson** [comment]
`.npmignore` fail.  :(  Thank you very much for letting me know about this issue!  It should be working now, please feel free to reopen if it is not.
